# Generated by Django 5.0.6 on 2024-05-26 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailData',
            fields=[
                ('nama', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.CharField(choices=[('HR', 'Devisi HR'), ('RnD', 'Devisi RnD'), ('Media', 'Devisi Media Informasi'), ('Engineering', 'Devisi Engineering'), ('Customers', 'Customers')], max_length=50)),
            ],
        ),
    ]
